### ISSUE TITLE
Writing - Prompt-engineering for grading

### ISSUE THREAD

**Issue by mzhubail** [bahrain-uob/gen-ai-moe-challenge#28]
**Input:** the writing question, the student’s answer 
**Output:** the grading of the student’s answer based on relevant metrics 

+ Look into the relevant metrics to grading the answer
+ Look into how feedback will be delivered
+ Look into what LLMs to use and how to formulate the prompt

**Comment by Ma-hawaj** [comment]
current prompt:

This is an answer of the following writing task:

Children who are brought up in families that do not have large amounts of money are better prepared to deal with the problems of adult life than children brought up by wealthy parents.
To what extent do you agree or disagree with this opinion?
Give reasons for your answer and include any relevant examples from your own knowledge or experience.
Write at least 250 words.

" I do agree to the statement that children brought up in poor families are better prepared to deal with the problems of adult life than children brought up by wealthy parents.
Children of poor parents are prematurely exposed to the problems of adult life eg. learning to survive on a low family income and sacrificing luxuries for essential items. These children begin to see the 'realities' of life in their home or social environment. Their parents own struggles serve as an example to them.
These children are taught necessary skills for survival as an adult from very early age. Many children eg work in the weekends or holidays to either collect some pocket money or even contribute to their familie's income. A good example is the many children who accompany their parents to sell produce at the market. They are making a direct contribution to their families in terms of labor or income.
Children of poor families also are highly motivated. They tend to set high goals to improve their economic and social situation. A relevant example would be Mr Bill Gates ( founder of Microsoft Corporation ) He had an impovenshed background but he used his talent and motivation to set up the worlds largest computer organisation.
However, there are some problems that children form poor backgrounds do encounter. Many of these children who are 'robbed' of their childhood eg while working, may feel cheated. They often turn to crime This however, is a small group.
In summing up, children with impovenshed backgrounds are able to deal with problems of adult life because of early exposure, family role models and sheer motivation."

Consider yourself an IELTS examiner and give me feedback on this answer taking in consideration task achievement, Coherence and cohesion, Grammatical range and accuracy, and lexical resources and give it a grade from 1 to 9. And try to reference where improvements can be made.

**Comment by Ma-hawaj** [comment]
added a route /writing to the api gate way that calls bedrock use the following command

`curl --location 'https://1x4bsj79i2.execute-api.us-east-1.amazonaws.com/writing' \
--header 'Content-Type: application/json' \
--data '{
    "prompt": "Hello"
}'
`

in the following commit
c099c52b5bd20dcad5c3588e02c12b252a4b32fb 

in the branch 28-writing-prompt-engineering-for-grading

**Comment by mzhubail** [comment]
> I have added some sample task 2 writing answer, from the internet, alongside the feedback. They're in teams under the folder 'Sample Writings'.
> 
> For now we'll be focusing on grading task 2, the 'simpler' one. Note that task 1 has a diagram as part of the question, which has to be fed to the model we'll use for grading; we'll look into that later.

As I've mentioned, this concerns task 2 only, which was completed.  A new Issue will be opened for Writing Task 1.
